version: '2.4'
services:
  sut:
    image: appropriate/curl
    command: ["--ipv4","--retry", "15","--retry-delay","5","--retry-connrefused","http://bookstack:8080/login"]
    depends_on:
    - bookstack
  mysql:
    image: mysql:8.1
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=secret
    volumes:
    - mysql-data:/var/lib/mysql

  bookstack:
    image: ${BOOKSTACK_IMAGE:-solidnerd/bookstack}
    depends_on:
    - mysql
    environment:
    - APP_URL=http://localhost:${DEV_PORT:-8080}
    - APP_KEY=SomeRandomStringWith32Characters
    - DB_HOST=mysql:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=secret
    volumes:
    - uploads:/var/www/bookstack/public/uploads
    - storage-uploads:/var/www/bookstack/storage/uploads
    ports:
    - "8080:80"

volumes:
 mysql-data:
 uploads:
 storage-uploads:
