version: 2
jobs:
  shellcheck:
    docker:
      - image: nlknguyen/alpine-shellcheck:v0.4.6
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck -e SC2086 -e SC1090 --external-sources

  build-deploy-e2e:
    docker:
    - image: circleci/golang:1.11.5
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Create docker image
        command: make build
    - run:
        name: Run E2E Test
        command: make e2e
    - run:
        name: Push docker image
        command: |
          if [[ -z "${CIRCLE_PULL_REQUEST}" ]] && [[ "${CIRCLE_PROJECT_USERNAME}" = "solidnerd" ]] ; then
            echo $docker_password | docker login --username $docker_user --password-stdin
            make push
          else
            echo "Do not push image"
          fi
  release:
    docker:
    - image: circleci/golang:1.11.5
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Login to public Docker HUB
        command: |
            docker login -u $docker_release_user -p $docker_release_password
            make release

workflows:
  version: 2
  build-and-verify:
    jobs:
      - shellcheck
      - build-deploy-e2e:
          requires:
            - shellcheck
  release:
    jobs:
      - release:
          filters:
            tags:
              only: /^([0-9]\d*)\.([0-9]\d*)\.([0-9]\d*).*$/
            branches:
              ignore: /.*/
